### ISSUE TITLE
implement multiple outputs in get_text_output wrapper

### ISSUE THREAD

**Issue by jonathanlastmileai** [lastmile-ai/aiconfig#427] opened 2023-12-07 21:21 UTC
Context: https://github.com/lastmile-ai/aiconfig/pull/421#discussion_r1419581757

**Comment by saqadri** [comment] 2023-12-15 21:47
Dupe of #467. Closing for now.

**Closed by saqadri** 2023-12-15 21:47 UTC
Labels: type: enhancement, pri: mid, status: planned

**Comment by jonathanlastmileai** [comment] 2023-12-15 23:20
@saqadri , this is not a quite a duplicate because `run_and_get_output_text` also hard-codes just returning the first result: https://github.com/lastmile-ai/aiconfig/blob/ebe5f0f84d48d0597873e2e598126ee4def9bf05/python/src/aiconfig/Config.py#L355
